import os
clear = lambda: os.system('cls')
clear()

print('Мы изучаем язык Python')
print('Python')
print("Python")
print('Скоро я', 'буду программировать', 'на языке', 'Python!')
print('1', '2', '4', '8', '16')
print('Какой хороший день!')
print('Работать мне не лень!')
print('Какой хороший день!')
print()
print('Работать мне не лень!')
print('В тексте есть "двойные" кавычки')
print("В тексте есть 'одинарные' кавычки")