import os
clear = lambda: os.system('cls')
clear()

print('a', 'b', 'c')
print('d', 'e', 'f')
print('a', 'b', 'c', sep='*')
print('d', 'e', 'f', sep='**')
print('a', 'b', 'c', end='@')
print('d', 'e', 'f', end='@@')
print('a', 'b', 'c', sep='*', end='finish')
print('d', 'e', 'f', sep='**', end='^__^')
print('g', 'h', 'i', sep='+', end='%')
print('j', 'k', 'l', sep='-', end='#')
print('m', 'n', 'o', sep='/', end='!')